server:
  url: "https://matrix.org"
  user: portfolio
  password: botpassword
  prefix: "portfolio:"
sqlserver:
  connstr: "sqlite+aiosqlite:///./data/database.db"
  connstr: "postgresql+asyncpg://scott:tiger@localhost/test"
  #connstr: "mysql+aiomysql://user:password@host:port/dbname"
datasources:
  updateall: False