version: "2"
services:
  tradebot:
    build: .
    restart: always
    volumes:
      - ./data:/data
    healthcheck:
      test: curl --fail http://localhost:9998/status || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s